# Generated by Django 3.0.8 on 2020-08-08 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='volunteercategory',
            options={'verbose_name_plural': 'volunteer categories'},
        ),
    ]
