# Generated by Django 3.0.8 on 2020-08-08 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('volunteer_categories', '0002_auto_20200807_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='volunteer_categories.Role'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='role',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='volunteer_categories.VolunteerCategory'),
        ),
        migrations.AlterField(
            model_name='volunteercategory',
            name='category_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category_types', to='volunteer_categories.CategoryType'),
        ),
    ]
