# Generated by Django 3.0.8 on 2020-08-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_categories', '0004_auto_20200808_2105'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='request',
            constraint=models.UniqueConstraint(fields=('user', 'role'), name='unique appversion'),
        ),
    ]
