# Generated by Django 3.0.8 on 2022-12-27 07:14

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_categories', '0005_auto_20200814_0029'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_date', models.DateTimeField()),
            ],
            managers=[
                ('dates', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='volunteercategory',
            name='category_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='category_types', to='volunteer_categories.CategoryType'),
        ),
    ]
