# Generated by Django 3.0.8 on 2025-12-07 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteer_categories', '0006_auto_20221227_0014'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['status'], name='volunteer_c_status_acfa87_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['user', 'status'], name='volunteer_c_user_id_7c169c_idx'),
        ),
        migrations.AddIndex(
            model_name='request',
            index=models.Index(fields=['role', 'status'], name='volunteer_c_role_id_cae791_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteercategory',
            index=models.Index(fields=['start_time', 'end_time'], name='volunteer_c_start_t_d5ade0_idx'),
        ),
        migrations.AddIndex(
            model_name='volunteercategory',
            index=models.Index(fields=['category_type'], name='volunteer_c_categor_ff8539_idx'),
        ),
    ]
