# Generated by Django 3.0.8 on 2020-07-23 05:15

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('scheduleEvent', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='scheduleevent',
            managers=[
                ('events', django.db.models.manager.Manager()),
            ],
        ),
    ]
